// lcd.h
#ifndef lcd_h
#define lcd_h


#define DDRAM_ADDRESS_SECOND_LINE 0x40
#define DDRAM_ADDRESS_FIRST_LINE 0x0

#define INSTRUCTION_DISPLAY_CLEAR_Pos 0
#define INSTRUCTION_CURSOR_HOME_Pos 1
#define INSTRUCTION_ENTRY_MODE_SET_Pos 2
#define INSTRUCTION_DISPLAY_ON_OFF_Pos 3
#define INSTRUCTION_CURSOR_SHIFT_Pos 4
#define INSTRUCTION_FUNCTION_SET_Pos 5

#define INSTRUCTION_DDRAM_ADDRESS_SET_Pos 7

#define INSTRUCTION_DISPLAY_CLEAR_Msk (1 << INSTRUCTION_DISPLAY_CLEAR_Pos)
#define INSTRUCTION_CURSOR_HOME_Msk (1 << INSTRUCTION_CURSOR_HOME_Pos)
#define INSTRUCTION_ENTRY_MODE_SET_Msk (1 << INSTRUCTION_ENTRY_MODE_SET_Pos)
#define INSTRUCTION_DISPLAY_ON_OFF_Msk (1 << INSTRUCTION_DISPLAY_ON_OFF_Pos)
#define INSTRUCTION_CURSOR_SHIFT_Msk (1 << INSTRUCTION_CURSOR_SHIFT_Pos)
#define INSTRUCTION_FUNCTION_SET_Msk (1 << INSTRUCTION_FUNCTION_SET_Pos)
#define INSTRUCTION_DDRAM_ADDRESS_SET_Msk (1 << INSTRUCTION_DDRAM_ADDRESS_SET_Pos)


#define DISPLAY_DELAY 3000
#define DELAY_SETUP_TIME 1

enum Line {
	FIRST,
	SECOND
};

#endif
